title:             Christophe Foyer
email:             christophe@cfoyer.com
description:       A gallery of my favorite pictures
author:            Christophe Foyer
baseurl:           "/"
url:               "http://gallery.cfoyer.com"

# Social Profiles
github_username:   Christophe-Foyer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
