title:             Christophe Foyer
email:             christophe@cfoyer.com
description:       A random collection of pictures
author:            Christophe Foyer
baseurl:           "/"
url:               "http://gallery.cfoyer.com"

# Social Profiles
github_username:   Christophe-Foyer
flickr_username:   135573610@N03
instagram_username:   christophe_Foyer
linkedin_username:   christophe-foyer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

#Google Analytics  
google_analytics: UA-116335955-4
  
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: cfoyer