title:             Christophe Foyer
email:             christophe@cfoyer.com
description:       A gallery of my favorite pictures
author:            Christophe Foyer
baseurl:           "/"
url:               "http://gallery.cfoyer.com"

# Social Profiles
github_username:   Christophe-Foyer
flickr_username:   christophe.foyer
instagram_username:Christophe_Foyer

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: cfoyer